site_name: Mixy
site_url: https://mixylabs.github.io/docs
copyright: Copyright © 2025 MrMati
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
#    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow
#    - toc.integrate
  palette:
    scheme: slate
    primary: blue grey
    accent: lime
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: lime
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: lime
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

markdown_extensions:
  - admonition
  - pymdownx.details


nav:
  - Home: README.md
  - Getting Started:
      - Device setup: getting_started/device_setup.md
      - Software selection: getting_started/software_selection.md
      - Software config:
          - Mixy Connect: getting_started/software_config/setup_mixy_connect.md
          - Meej: getting_started/software_config/setup_meej.md
  - Customization:
    - Hardware: customization/hardware.md
  - FAQ: FAQ.md


extra_css:
  - overrides/extra.css